### ISSUE TITLE
Responce is nothing

### ISSUE THREAD

**Issue by Kansei** [arabian9ts/GroupMorning#20]
空のデータベースの状態で新規にグループを作るとデータベースへの登録はできるが、サーバーからデータベースのデータが送られてこない。
他の状況でもデーターが送られてこない時がある。

**Comment by arabian9ts** [comment]
ユーザ名とアラーム時刻をセットする画面で、時間を変更しなかったときにリクエストのtimeパラメータが空になっています。

**Comment by Kansei** [comment]
timeに現在時刻を入れたが改善されなかった。
また、データベースからデータが送られこなかった後に、アプリを起動したままデータベースのデータを消してもう一度グループを作成すると正常に動いた。

**Comment by arabian9ts** [comment]
timeに現在時刻を入れたときのリクエストurlはどうなってる？
正常に動作したときのリクエストurlと比較してみるといいかも。

**Comment by Kansei** [comment]
httpリクエストをgetにしていながら、railsから何もレスポンスを送っていなかったことが原因でした。 
簡単なエラー処理を加えました。
